import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import { Layout, Typography, Card, Button, Space, Row, Col } from 'antd';
import { GithubOutlined, BookOutlined } from '@ant-design/icons';

import { api } from "../utils/api";

const { Content } = Layout;
const { Title, Text, Link } = Typography;

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Content style={{ minHeight: '100vh', background: 'linear-gradient(to bottom, #2e026d, #15162c)' }}>
          <div style={{ maxWidth: 1200, margin: '0 auto', padding: '4rem 2rem' }}>
            <Title style={{ textAlign: 'center', color: 'white', fontSize: '4rem', marginBottom: '3rem' }}>
              Create <span style={{ color: 'hsl(280,100%,70%)' }}>T3</span> App
            </Title>
            
            <Row gutter={[24, 24]} justify="center">
              <Col xs={24} sm={12}>
                <Card
                  hoverable
                  style={{ background: 'rgba(255, 255, 255, 0.1)', borderColor: 'transparent' }}
                  bodyStyle={{ color: 'white' }}
                >
                  <Link href="https://create.t3.gg/en/usage/first-steps" target="_blank" style={{ color: 'white' }}>
                    <Title level={3} style={{ color: 'white' }}>
                      <BookOutlined /> First Steps →
                    </Title>
                    <Text style={{ color: 'white', fontSize: '1.1rem' }}>
                      Just the basics - Everything you need to know to set up your
                      database and authentication.
                    </Text>
                  </Link>
                </Card>
              </Col>
              <Col xs={24} sm={12}>
                <Card
                  hoverable
                  style={{ background: 'rgba(255, 255, 255, 0.1)', borderColor: 'transparent' }}
                  bodyStyle={{ color: 'white' }}
                >
                  <Link href="https://create.t3.gg/en/introduction" target="_blank" style={{ color: 'white' }}>
                    <Title level={3} style={{ color: 'white' }}>
                      <GithubOutlined /> Documentation →
                    </Title>
                    <Text style={{ color: 'white', fontSize: '1.1rem' }}>
                      Learn more about Create T3 App, the libraries it uses, and how
                      to deploy it.
                    </Text>
                  </Link>
                </Card>
              </Col>
            </Row>

            <Space direction="vertical" align="center" style={{ width: '100%', marginTop: '3rem' }}>
              <Text style={{ fontSize: '1.5rem', color: 'white' }}>
                {hello.data ? hello.data.greeting : "Loading tRPC query..."}
              </Text>
              <AuthShowcase />
            </Space>
          </div>
        </Content>
      </Layout>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined,
    { enabled: sessionData?.user !== undefined },
  );

  return (
    <Space direction="vertical" align="center" size="large">
      <Text style={{ fontSize: '1.5rem', color: 'white', textAlign: 'center' }}>
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </Text>
      <Button
        type="default"
        size="large"
        style={{ 
          color: 'white',
          borderColor: 'rgba(255, 255, 255, 0.1)',
          background: 'rgba(255, 255, 255, 0.1)',
        }}
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </Button>
    </Space>
  );
};
